---
- name: Example playbook with 10-minute wait time
  hosts: localhost
  connection: local
  become: yes

  tasks:
  
    - name: Perform initial action
      ansible.built.command: sleep 600

        
        
  
  
